# Python CircleCI 2.1 configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12

    working_directory: ~/repo

    steps:
      # Step 1: Checkout the repository from GitHub
      - checkout

      # Step 2: Create a virtual environment and install dependencies
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      # Step 3: Run linter and tests
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator calculator/

